Repository bcgov/MOH-MAiD, pull requests merged in 2023-04, with the labels that each got.

#611 BCMOHAD-14385 || Fix report fields issue
  MAiD - Case Management App/force-app/main/default/objects/Case/fields/Preferred_Gender__c.field-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/RAC_Q05I__c.field-meta.xml
  MAiD - Case Management App/force-app/main/default/reports/MAiDCaseManagementReports/S2_2023_HC_ReportOral_MAiD_P8M.report-meta.xml
  MAiD - Case Management App/force-app/main/default/reports/MAiDCaseManagementReports/S5_2023_HC_Report_Withdrawal_lhD.report-meta.xml
  MAiD - Case Management App/force-app/main/default/reports/MAiDCaseManagementReports/S7_2023_HC_ReportDied_Prior_XPB.report-meta.xml
Labels: bug

#557 BCMOHAD-14316 || Add User Mappings and Registration to git
  MAiD - Case Management App/.forceignore
  MAiD - Case Management App/force-app/main/default/customMetadata/IDP_User_Registration_Permission_Set.MAiD_Analyst.md-meta.xml
  MAiD - Case Management App/force-app/main/default/customMetadata/IDP_User_Registration_Permission_Set.MAiD_Manager_1.md-meta.xml
  MAiD - Case Management App/force-app/main/default/customMetadata/IDP_User_Registration_Permission_Set.MAiD_Manager_2.md-meta.xml
  MAiD - Case Management App/force-app/main/default/customMetadata/IDP_User_Registration_Permission_Set.MAiD_Manager_3.md-meta.xml
  MAiD - Case Management App/force-app/main/default/customMetadata/IDP_User_Registration_Permission_Set.MAiD_Manager_4.md-meta.xml
  MAiD - Case Management App/force-app/main/default/customMetadata/IDP_User_Registration_Permission_Set.MAiD_System_Administrator.md-meta.xml
  MAiD - Case Management App/force-app/main/default/customMetadata/IDP_User_Registration_User_Mapping.MAiD_Analyst.md-meta.xml
  MAiD - Case Management App/force-app/main/default/customMetadata/IDP_User_Registration_User_Mapping.MAiD_Manager_1.md-meta.xml
  MAiD - Case Management App/force-app/main/default/customMetadata/IDP_User_Registration_User_Mapping.MAiD_Manager_2.md-meta.xml
  MAiD - Case Management App/force-app/main/default/customMetadata/IDP_User_Registration_User_Mapping.MAiD_Manager_3.md-meta.xml
  MAiD - Case Management App/force-app/main/default/customMetadata/IDP_User_Registration_User_Mapping.MAiD_Manager_4.md-meta.xml
  MAiD - Case Management App/force-app/main/default/customMetadata/IDP_User_Registration_User_Mapping.MAiD_System_Administrator.md-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/IDP_User_Registration_Permission_Set__mdt/IDP_User_Registration_Permission_Set__mdt.object-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/IDP_User_Registration_Permission_Set__mdt/fields/Assignment_Type__c.field-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/IDP_User_Registration_Permission_Set__mdt/fields/External_Provider_User_Mapping__c.field-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/IDP_User_Registration_Permission_Set__mdt/fields/Salesforce_Permission_Set_Group__c.field-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/IDP_User_Registration_Permission_Set__mdt/fields/Salesforce_Permission_Set__c.field-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/IDP_User_Registration_Permission_Set__mdt/listViews/All_Details.listView-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/IDP_User_Registration_Permission_Set__mdt/validationRules/Permission_Set_or_Permission_Set_Group.validationRule-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/IDP_User_Registration_User_Mapping__mdt/IDP_User_Registration_User_Mapping__mdt.object-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/IDP_User_Registration_User_Mapping__mdt/fields/Assurance_Level__c.field-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/IDP_User_Registration_User_Mapping__mdt/fields/External_Provider_Role__c.field-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/IDP_User_Registration_User_Mapping__mdt/fields/Identity_Provider__c.field-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/IDP_User_Registration_User_Mapping__mdt/fields/MFA_Flag__c.field-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/IDP_User_Registration_User_Mapping__mdt/fields/Salesforce_User_License__c.field-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/IDP_User_Registration_User_Mapping__mdt/fields/Salesforce_User_Profile__c.field-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/IDP_User_Registration_User_Mapping__mdt/fields/Salesforce_User_Role__c.field-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/IDP_User_Registration_User_Mapping__mdt/fields/Sequence__c.field-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/IDP_User_Registration_User_Mapping__mdt/listViews/All_Data.listView-meta.xml
Labels: enhancement

#612 BCMOHAD-14584 Rule 46 Changes reverted to Original Version
  MAiD - Case Management App/force-app/main/default/flows/Mandatory_Data.flow-meta.xml
Labels: enhancement

#614 BCMOHAD-14824 Rules 57, 58, 25 Updated
  MAiD - Case Management App/force-app/main/default/flows/Mandatory_Data.flow-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/Form_1634__c/fields/Types_of_palliative_care_received__c.field-meta.xml
Labels: enhancement

#613 BCMOHAD-14354 || Added Page layout and the flow
  MAiD - Case Management App/force-app/main/default/flows/Case_After_Update_Reportable_to_Health_Canada_BCCS_Manager_Review_Required_Rule.flow-meta.xml
  MAiD - Case Management App/force-app/main/default/layouts/Case-MAiD Error Log.layout-meta.xml
Labels: enhancement

#615 BCMOHAD-14824 Picklist Label Change for Rule 25 Update
  MAiD - Case Management App/force-app/main/default/objects/Form_1634__c/fields/Types_of_palliative_care_received__c.field-meta.xml
Labels: enhancement

#616 BCMOHAD-14824 || Fix Formula fields.
  MAiD - Case Management App/.sf/config.json
  MAiD - Case Management App/force-app/main/default/flows/Case_After_Update_Reportable_to_Health_Canada_BCCS_Manager_Review_Required_Rule.flow-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/Form_1634__c/fields/ELG_Q85_Formula__c.field-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/Form_1634__c/fields/ELG_Q90_Formula__c.field-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/Form_1634__c/fields/Length_of_assessment_period__c.field-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/Form_1634__c/fields/SLF_S11__c.field-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/ELG_Q40A__c.field-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/ELG_Q40B__c.field-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/ELG_Q51I__c.field-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/ELG_Q86A__c.field-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/ELG_Q87J__c.field-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/ELG_S72G__c.field-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/SLF_Q50__c.field-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/SPC_Q16__c.field-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/SPC_S16__c.field-meta.xml
Labels: bug, enhancement

#618 BCMOHAD-14236 || Updated the Global Picklist Valueset
  MAiD - Case Management App/force-app/main/default/globalValueSets/Missed_Error_Log_Issue.globalValueSet-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/Case/fields/Impacted_Form__c.field-meta.xml
Labels: enhancement

#619 BCMOHAD-14463 Rule 60 Updated
  MAiD - Case Management App/force-app/main/default/flows/Provincial_and_RX_Flow_for_1633.flow-meta.xml
Labels: enhancement

#620 BCMOHAD-14985 Rule 68 Update
  MAiD - Case Management App/force-app/main/default/flows/Mandatory_Data.flow-meta.xml
Labels: enhancement

#621 BCMOHAD-14984 Rule 48 Update
  MAiD - Case Management App/force-app/main/default/flows/Mandatory_Data.flow-meta.xml
Labels: enhancement

#622 BCMOHAD-14994 Rule 57 Updated
  MAiD - Case Management App/force-app/main/default/flows/Mandatory_Data.flow-meta.xml
Labels: enhancement

#623 BCMOHAD-14995 Rule 58 Update
  MAiD - Case Management App/force-app/main/default/flows/Mandatory_Data.flow-meta.xml
Labels: enhancement

#625 BCMOHAD-14981 || Fix Duplicate PHN flow.
  MAiD - Case Management App/force-app/main/default/flows/MAiD_Prevent_Duplicate_Phn.flow-meta.xml
Labels: bug

#624 BCMOHAD-15001 Case_After_Update_Reportable_to_Health_Canada_BCCS_Mana…
  MAiD - Case Management App/force-app/main/default/flows/Case_After_Update_Reportable_to_Health_Canada_BCCS_Manager_Review_Required_Rule.flow-meta.xml
Labels: enhancement

#626 BCMOHAD-14824 Rule 66 and Health Canada Rule Update
  MAiD - Case Management App/force-app/main/default/flows/Case_After_Update_Reportable_to_Health_Canada_BCCS_Manager_Review_Required_Rule.flow-meta.xml
  MAiD - Case Management App/force-app/main/default/flows/Federal_Safeguards.flow-meta.xml
Labels: enhancement

#627 BCMOHAD-14824 Rule 66 fix
  MAiD - Case Management App/force-app/main/default/flows/Federal_Safeguards.flow-meta.xml
Labels: enhancement

#628 BCMOHAD-15036 Fields added to the 1634 PageLayout
  MAiD - Case Management App/force-app/main/default/layouts/Form_1634__c-Form 1634 Layout.layout-meta.xml
Labels: enhancement

#629 BCMOHAD-15040 Rule 50 Update
  MAiD - Case Management App/force-app/main/default/flows/Mandatory_Data.flow-meta.xml
Labels: enhancement

#631 BCMOHAD-15057 || Move fields in page layout.
  MAiD - Case Management App/force-app/main/default/layouts/Case-MAiD Case Layout.layout-meta.xml
Labels: bug

#632 BCMOHAD-15036 PHA_Q16 formula field updated on Form_1641__C Object
  MAiD - Case Management App/force-app/main/default/objects/Form_1641__c/fields/PHA_Q16__c.field-meta.xml
Labels: enhancement

#633 BCMOHAD-15072 Medication dosage/time value added to the "Missed Issue on Form RX/MAR field" picklist
  MAiD - Case Management App/force-app/main/default/objects/Case/fields/Missed_Issue_on_Form_RX_MAR__c.field-meta.xml
Labels: bug, enhancement

#634 BCMOHAD-15040 Rule 50 Update
  MAiD - Case Management App/force-app/main/default/flows/Mandatory_Data.flow-meta.xml
Labels: bug

#635 BCMOHAD-15036 PHA_Q16 field formula update on Form 1641
  MAiD - Case Management App/force-app/main/default/objects/Form_1641__c/fields/PHA_Q16__c.field-meta.xml
Labels: bug

#630 BCMOHAD-15037 || Update duplicate PHN rule
  MAiD - Case Management App/force-app/main/default/flows/MAiD_Prevent_Duplicate_Phn.flow-meta.xml
Labels: bug
