Repository bcgov/MOH-MAiD, pull requests merged in 2023-03, with the labels that each got.

#522 Bcmohad 13629 v1 || updated flow with bug fixes
  MAiD - Case Management App/force-app/main/default/flows/MAiD_Prevent_Duplicate_Phn.flow-meta.xml
Labels: bug

#524 BCMOHAD-14077||Added New Report
  MAiD - Case Management App/force-app/main/default/reports/MAiDCaseManagementReports/S7_2023_HC_ReportDied_Prior_XPB.report-meta.xml
Labels: enhancement

#521 BCMOHAD-14029 || Add missing fields.
  MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/PROC_Q185B__c.field-meta.xml
  MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Analyst.permissionset-meta.xml
  MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Manager.permissionset-meta.xml
  MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_System_Administrator.permissionset-meta.xml
  MAiD - Case Management App/force-app/main/default/reportTypes/Form_1634_with_S1_HC_2023.reportType-meta.xml
  MAiD - Case Management App/force-app/main/default/reports/MAiDCaseManagementReports/S1_Admin_Substance_HC_2023Report.report-meta.xml
Labels: bug

#525 BCMOHAD-14029 || Remove MDR1_Q05__c field from metadata.
  MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Analyst.permissionset-meta.xml
  MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Manager.permissionset-meta.xml
  MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_System_Administrator.permissionset-meta.xml
  MAiD - Case Management App/force-app/main/default/reportTypes/Form_1634_with_S1_HC_2023.reportType-meta.xml
Labels: bug

#526 BCMOHAD - 14126 Updated Page Layout
  MAiD - Case Management App/force-app/main/default/layouts/Form_1634__c-Form 1634 Layout.layout-meta.xml
Labels: enhancement

#527 BCMOHAD-14077||Added New Formula Fields
  MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/COD_Q40A__c.field-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/COD_Q40B__c.field-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/COD_Q40C__c.field-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/COD_Q40D__c.field-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/COD_Q40E__c.field-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/COD_Q40F__c.field-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/COD_Q40G__c.field-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/COD_Q40H__c.field-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/COD_Q40I__c.field-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/COD_Q40J__c.field-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/COD_S40I__c.field-meta.xml
  MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Analyst.permissionset-meta.xml
  MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Manager.permissionset-meta.xml
  MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Reports_Dashboards.permissionset-meta.xml
  MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_System_Administrator.permissionset-meta.xml
  MAiD - Case Management App/force-app/main/default/reports/MAiDCaseManagementReports/S7_2023_HC_ReportDied_Prior_XPB.report-meta.xml
Labels: enhancement

#528 BCMOHAD-14077 || Updated Report Type
  MAiD - Case Management App/force-app/main/default/reportTypes/Form_1634_with_S1_HC_2023.reportType-meta.xml
  MAiD - Case Management App/force-app/main/default/reports/MAiDCaseManagementReports/S7_2023_HC_ReportDied_Prior_XPB.report-meta.xml
Labels: bug

#529 BCMOHAD-14093 || Rule 45 Change
  MAiD - Case Management App/force-app/main/default/flows/Mandatory_Data.flow-meta.xml
Labels: enhancement

#532 BCMOHAD-14077||Changed position of few fields
  MAiD - Case Management App/force-app/main/default/reports/MAiDCaseManagementReports/S7_2023_HC_ReportDied_Prior_XPB.report-meta.xml
Labels: bug

#531 BCMOHAD-14191 New criteria added in Rule 27
  MAiD - Case Management App/force-app/main/default/flows/Provincial_Safeguards.flow-meta.xml
Labels: enhancement

#534 Bcmohad 14192
  MAiD - Case Management App/force-app/main/default/flows/Provincial_Safeguards.flow-meta.xml
Labels: enhancement

#535 BCMOHAD-14177 Rule 3 Updated
  MAiD - Case Management App/force-app/main/default/flows/Legislation_Safeguards.flow-meta.xml
Labels: enhancement

#537 BCMOHAD-14076 || Created the Report and Fields
  MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/WOR_Q15A__c.field-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/WOR_Q15B__c.field-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/WOR_Q15C__c.field-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/WOR_Q15D__c.field-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/WOR_Q15E__c.field-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/WOR_Q15F__c.field-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/WOR_Q20A__c.field-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/WOR_Q20B__c.field-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/WOR_Q20C__c.field-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/WOR_Q20D__c.field-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/WOR_Q20E__c.field-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/WOR_Q20F__c.field-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/WOR_Q20G__c.field-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/WOR_Q20H__c.field-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/WOR_Q20I__c.field-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/WOR_Q20J__c.field-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/WOR_S15E__c.field-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/WOR_S20J__c.field-meta.xml
  MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Analyst.permissionset-meta.xml
  MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Manager.permissionset-meta.xml
  MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_System_Administrator.permissionset-meta.xml
  MAiD - Case Management App/force-app/main/default/reportTypes/Form_1634_with_S1_HC_2023.reportType-meta.xml
  MAiD - Case Management App/force-app/main/default/reports/MAiDCaseManagementReports/S5_2023_HC_Report_Withdrawal_lhD.report-meta.xml
Labels: enhancement

#538 BCMOHAD-14191
  MAiD - Case Management App/force-app/main/default/flows/Provincial_Safeguards.flow-meta.xml
Labels: enhancement

#539 BCMOHAD-14183||updated flow
  MAiD - Case Management App/force-app/main/default/flows/Federal_Safeguards.flow-meta.xml
Labels: enhancement

#542 BCMOHAD-14076 || Added Supplementary Info field in the report
  MAiD - Case Management App/force-app/main/default/reports/MAiDCaseManagementReports/S5_2023_HC_Report_Withdrawal_lhD.report-meta.xml
Labels: good first issue

#546 BCMOHAD-14192 Rule 29 Updated
  MAiD - Case Management App/force-app/main/default/flows/Provincial_Safeguards.flow-meta.xml
Labels: enhancement

#543 BCMOHAD-14178 Rule 4 Updated
  MAiD - Case Management App/force-app/main/default/flows/Legislation_Safeguards.flow-meta.xml
Labels: enhancement

#544 BCMOHAD-14179 Rule 5 Updated
  MAiD - Case Management App/force-app/main/default/flows/Legislation_Safeguards.flow-meta.xml
Labels: enhancement

#545 BCMOHAD-14180 Rule 6 Updated
  MAiD - Case Management App/force-app/main/default/flows/Legislation_Safeguards.flow-meta.xml
Labels: enhancement

#548 BCMOHAD-14185 Rule 12 Updated
  MAiD - Case Management App/force-app/main/default/flows/Federal_Safeguards.flow-meta.xml
Labels: enhancement

#549 BCMOHAD-14192
  MAiD - Case Management App/force-app/main/default/flows/Provincial_Safeguards.flow-meta.xml
Labels: enhancement

#550 BCMOHAD-14075 || Add S6 2023 Health Canada-Ineligible
  MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/ELG_Q130__c.field-meta.xml
  MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Analyst.permissionset-meta.xml
  MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Manager.permissionset-meta.xml
  MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Reports_Dashboards.permissionset-meta.xml
  MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_System_Administrator.permissionset-meta.xml
  MAiD - Case Management App/force-app/main/default/reports/MAiDCaseManagementReports/S6_2023_Health_CanadaIneligible_G9B.report-meta.xml
Labels: enhancement

#551 BCMOHAD-14075 v1 || Add missing report type file
  MAiD - Case Management App/.sf/config.json
  MAiD - Case Management App/force-app/main/default/reportTypes/Form_1634_with_S1_HC_2023.reportType-meta.xml
Labels: bug

#552 Bcmohad 14183 || updated rule
  MAiD - Case Management App/force-app/main/default/flows/Federal_Safeguards.flow-meta.xml
Labels: enhancement

#556 BCMOHAD-14078 || Add new 1641 Report
  MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/PHA_Q16__c.field-meta.xml
  MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Analyst.permissionset-meta.xml
  MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Manager.permissionset-meta.xml
  MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Reports_Dashboards.permissionset-meta.xml
  MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_System_Administrator.permissionset-meta.xml
  MAiD - Case Management App/force-app/main/default/reportTypes/Form_1634_with_S1_HC_2023.reportType-meta.xml
  MAiD - Case Management App/force-app/main/default/reports/MAiDCaseManagementReports/X1641_2023_Pharmacist_Report_nr4.report-meta.xml
Labels: enhancement

#559 BCMOHAD-14078 v1 || Rearrange fields to new report as per Lara feedback
  MAiD - Case Management App/.gitignore
  MAiD - Case Management App/force-app/main/default/objects/Form_1641__c/fields/PHA_Q16__c.field-meta.xml
  MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Analyst.permissionset-meta.xml
  MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Manager.permissionset-meta.xml
  MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Reports_Dashboards.permissionset-meta.xml
  MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_System_Administrator.permissionset-meta.xml
  MAiD - Case Management App/force-app/main/default/reportTypes/Form_1634_with_S1_HC_2023.reportType-meta.xml
  MAiD - Case Management App/force-app/main/default/reports/MAiDCaseManagementReports/X1641_2023_Pharmacist_Report_Y6x.report-meta.xml
  MAiD - Case Management App/force-app/main/default/reports/MAiDCaseManagementReports/X1641_2023_Pharmacist_Report_nr4.report-meta.xml
Labels: bug

#560 BCMOHAD- 14187 Rule 37 Updated
  MAiD - Case Management App/force-app/main/default/flows/Federal_Safeguards.flow-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/Form_1634__c/fields/Services_offered_or_discussed__c.field-meta.xml
Labels: enhancement

#561 BCMOHAD-14181 || Updated Rule 7
  MAiD - Case Management App/force-app/main/default/flows/Legislation_Safeguards.flow-meta.xml
Labels: enhancement

#564 BCMOHAD-14184 Rule 11 Update
  MAiD - Case Management App/force-app/main/default/flows/Federal_Safeguards.flow-meta.xml
Labels: enhancement

#565 BCMOHAD-14184 Rule 11 Update
  MAiD - Case Management App/force-app/main/default/flows/Federal_Safeguards.flow-meta.xml
Labels: enhancement

#567 BCMOHAD-14177 Rule 3 Update
  MAiD - Case Management App/force-app/main/default/flows/Legislation_Safeguards.flow-meta.xml
Labels: enhancement

#568 BCMOHAD-14178 Rule 4 Update
  MAiD - Case Management App/force-app/main/default/flows/Legislation_Safeguards.flow-meta.xml
Labels: enhancement

#569 BCMOHAD-14179 Rule 5 Update
  MAiD - Case Management App/force-app/main/default/flows/Legislation_Safeguards.flow-meta.xml
Labels: enhancement

#571 BCMOHAD-14191 Rule 27 Update
  MAiD - Case Management App/force-app/main/default/flows/Provincial_Safeguards.flow-meta.xml
Labels: enhancement

#572 BCMOHAD-14180 Rule 6 Update
  MAiD - Case Management App/force-app/main/default/flows/Legislation_Safeguards.flow-meta.xml
Labels: enhancement

#573 BCMOHAD-14195 | Rule 25
  MAiD - Case Management App/force-app/main/default/flows/Mandatory_Data.flow-meta.xml
Labels: enhancement

#576 BCMOHAD-14182 || Updated rule 47
  MAiD - Case Management App/force-app/main/default/flows/Legislation_Safeguards.flow-meta.xml
Labels: enhancement

#577 BCMOHAD-14078 v2 || Change Report type used in report as per Lara feedback
  MAiD - Case Management App/.sf/config.json
  MAiD - Case Management App/force-app/main/default/reports/MAiDCaseManagementReports/X1641_2023_Pharmacist_Report_Y6x.report-meta.xml
Labels: bug

#579 BCMOHAD-14190 Rule 66 Update
  MAiD - Case Management App/force-app/main/default/flows/Federal_Safeguards.flow-meta.xml
Labels: enhancement

#578 BCMOHAD-14195 -Rule 20, 25,26,33,42,50 -Updates
  MAiD - Case Management App/force-app/main/default/flows/Mandatory_Data.flow-meta.xml
  MAiD - Case Management App/force-app/main/default/layouts/Form_1634__c-Form 1634 Layout.layout-meta.xml
  MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Analyst.permissionset-meta.xml
  MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Manager.permissionset-meta.xml
Labels: enhancement

#581 BCMOHAD-14182-v1 || Updated Rule 47
  MAiD - Case Management App/force-app/main/default/flows/Legislation_Safeguards.flow-meta.xml
Labels: enhancement

#583 BCMOHAD-14379 || Rule 45 Change
  MAiD - Case Management App/force-app/main/default/flows/Mandatory_Data.flow-meta.xml
Labels: enhancement

#582 BCMOHAD-14184 Rule 11 Update
  MAiD - Case Management App/force-app/main/default/flows/Federal_Safeguards.flow-meta.xml
Labels: enhancement

#584 BCMOHAD-14202 || Rule 57 update
  MAiD - Case Management App/force-app/main/default/flows/Mandatory_Data.flow-meta.xml
Labels: enhancement

#585 BCMOHAD-14208 Status 5 flow Update
  MAiD - Case Management App/force-app/main/default/flows/Status_5_update_flow.flow-meta.xml
Labels: enhancement

#586 BCMOHAD-14209 Status flow 6 Updated
  MAiD - Case Management App/force-app/main/default/flows/Status6_Update.flow-meta.xml
Labels: enhancement

#587 BCMOHAD-14204 Rule 68 Update
  MAiD - Case Management App/force-app/main/default/flows/Mandatory_Data.flow-meta.xml
Labels: enhancement

#588 BCMOHAD-14205 Rule 69 Update
  MAiD - Case Management App/force-app/main/default/flows/Mandatory_Data.flow-meta.xml
Labels: enhancement

#590 BCMOHAD-14200 || Rule 46
  MAiD - Case Management App/force-app/main/default/flows/Mandatory_Data.flow-meta.xml
Labels: enhancement

#591 BCMOHAD-14184 Rule 11 Fix
  MAiD - Case Management App/force-app/main/default/flows/Federal_Safeguards.flow-meta.xml
Labels: enhancement

#592 BCMOHAD-14190 Rule 66 Fix
  MAiD - Case Management App/force-app/main/default/flows/Federal_Safeguards.flow-meta.xml
Labels: enhancement

#594 BCMOHAD-14200-V1 || Rule 46 Changes
  MAiD - Case Management App/force-app/main/default/flows/Mandatory_Data.flow-meta.xml
Labels: enhancement

#595 BCMOHAD-14204 Position of the Rules 67,68,69 Changed in the flow
  MAiD - Case Management App/force-app/main/default/flows/Mandatory_Data.flow-meta.xml
Labels: enhancement

#596 BCMOHAD-14461 || Rule 42 & 58 changes
  MAiD - Case Management App/force-app/main/default/flows/Mandatory_Data.flow-meta.xml
Labels: enhancement

#597 BCMOHAD-14204 Position error fixed
  MAiD - Case Management App/force-app/main/default/flows/Mandatory_Data.flow-meta.xml
Labels: enhancement

#598 BCMOHAD-14182-v1 || Updated the changes
  MAiD - Case Management App/force-app/main/default/flows/Legislation_Safeguards.flow-meta.xml
Labels: bug

#599 BCMOHAD-14462 Rule 48 Not Applicable from 2023 criteria added
  MAiD - Case Management App/force-app/main/default/flows/Mandatory_Data.flow-meta.xml
Labels: enhancement

#600 BCMOHAD-14204 Rule 68 Update
  MAiD - Case Management App/force-app/main/default/flows/Mandatory_Data.flow-meta.xml
Labels: enhancement

#601 BCMOHAD-14204 Rule 68 Update
  MAiD - Case Management App/force-app/main/default/flows/Mandatory_Data.flow-meta.xml
Labels: enhancement

#603 BCMOHAD-14182-v1 || Latest Updates
  MAiD - Case Management App/force-app/main/default/flows/Legislation_Safeguards.flow-meta.xml
Labels: bug, enhancement

#607 BCMOHAD-14584 || Rule 46 Change
  MAiD - Case Management App/force-app/main/default/flows/Mandatory_Data.flow-meta.xml
Labels: enhancement

#608 BCMOHAD-14204 Rule 68, 69 Update
  MAiD - Case Management App/force-app/main/default/flows/Mandatory_Data.flow-meta.xml
Labels: enhancement

#609 BCMOHAD-14462 Rule 48 Bypass Rule changes Reverted
  MAiD - Case Management App/force-app/main/default/flows/Mandatory_Data.flow-meta.xml
Labels: enhancement
