Repository bcgov/MOH-MAiD, pull requests merged in 2024-08, with the labels that each got.

#804 BCMOHMAD-24595 || Val rule and custom settings
  MAiD - Case Management App/force-app/main/default/objects/Form_1634__c/validationRules/Rule_42_Data_Check.validationRule-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/Maid_Validation_Settings__c/Maid_Validation_Settings__c.object-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/Maid_Validation_Settings__c/fields/Case_Type_Reported_Date__c.field-meta.xml
Labels: enhancement

#805 BCMOHAD-24539 || Update PS and Layout for Case
  MAiD - Case Management App/force-app/main/default/layouts/Case-MAiD Case Layout.layout-meta.xml
  MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Analyst.permissionset-meta.xml
Labels: enhancement

#808 BCMOHAD-24607 || Updated the formula field
  MAiD - Case Management App/force-app/main/default/objects/Case/recordTypes/MAiD_Case.recordType-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/SEX_Q06__c.field-meta.xml
Labels: enhancement

#809 Bcmohad 24606 || formula update RFD_Q05
  MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/RFD_Q05__c.field-meta.xml
Labels: enhancement

#810 BCMOHAD-24612 || Updated the field formula
  MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/IND_Q05D__c.field-meta.xml
Labels: enhancement

#811 BCMOHAD-24613 || Updated the formula
  MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/IND_Q05E__c.field-meta.xml
Labels: enhancement

#812 BCMOHAD-25000 || update DIS_Q25
  MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/DIS_Q25__c.field-meta.xml
Labels: enhancement

#813 Bcmohad 25002 || update formula DIS_Q30
  MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/DIS_Q30__c.field-meta.xml
Labels: enhancement

#814 BCMOHAD-24749 Update formula REQ_Q20
  MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/REQ_Q20__c.field-meta.xml
Labels: enhancement

#820 BCMOHAD-24595-1 || Update flow and remove new custom settings
  MAiD - Case Management App/force-app/main/default/flows/Mandatory_Data.flow-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/Form_1634__c/validationRules/Rule_42_Data_Check.validationRule-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/Maid_Validation_Settings__c/Maid_Validation_Settings__c.object-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/Maid_Validation_Settings__c/fields/Case_Type_Reported_Date__c.field-meta.xml
Labels: enhancement

#774 Bcmohad 23754 1 Adding additional ICY Communities
  MAiD - Case Management App/force-app/main/default/flows/ICY_Referral_Owner_Assignment_Flow.flow-meta.xml
  MAiD - Case Management App/force-app/main/default/groups/ICY_Cowichan_Valley_CL_NCL.group-meta.xml
  MAiD - Case Management App/force-app/main/default/groups/ICY_Delta_CL_NCL.group-meta.xml
  MAiD - Case Management App/force-app/main/default/groups/ICY_Gold_Trail_CL_NCL.group-meta.xml
  MAiD - Case Management App/force-app/main/default/groups/ICY_Nicola_Similkameen_CL_NCL.group-meta.xml
  MAiD - Case Management App/force-app/main/default/groups/ICY_Peace_River_South_CL_NCL.group-meta.xml
  MAiD - Case Management App/force-app/main/default/groups/ICY_Qualicum_CL_NCL.group-meta.xml
  MAiD - Case Management App/force-app/main/default/groups/ICY_Surrey_CL_NCL.group-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/Case/fields/ICY_Geographic_Area__c.field-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/Case/recordTypes/ICY_Close_Case.recordType-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/Case/recordTypes/ICY_Standard_Case.recordType-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/Referral__c/fields/ICY_Geographic_Area__c.field-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/Referral__c/recordTypes/ICY_General.recordType-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/Referral__c/recordTypes/ICY_General_Read_Only.recordType-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/Referral__c/recordTypes/ICY_Medical.recordType-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/Referral__c/recordTypes/ICY_Medical_Read_Only.recordType-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/Referral__c/recordTypes/Read_Only.recordType-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/System_Access_Request__c/fields/ICY_Community_Assigned__c.field-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/System_Access_Request__c/recordTypes/ICY.recordType-meta.xml
  MAiD - Case Management App/force-app/main/default/queues/ICY_Cowichan_Valley.queue-meta.xml
  MAiD - Case Management App/force-app/main/default/queues/ICY_Delta.queue-meta.xml
  MAiD - Case Management App/force-app/main/default/queues/ICY_Gold_Trail.queue-meta.xml
  MAiD - Case Management App/force-app/main/default/queues/ICY_Nicola_Similkameen.queue-meta.xml
  MAiD - Case Management App/force-app/main/default/queues/ICY_Peace_River_South.queue-meta.xml
  MAiD - Case Management App/force-app/main/default/queues/ICY_Qualicum.queue-meta.xml
  MAiD - Case Management App/force-app/main/default/queues/ICY_Surrey.queue-meta.xml
  MAiD - Case Management App/force-app/main/default/roles/Cowichan_Valley_Team_Admin.role-meta.xml
  MAiD - Case Management App/force-app/main/default/roles/Cowichan_Valley_Team_Clinical_Member.role-meta.xml
  MAiD - Case Management App/force-app/main/default/roles/Cowichan_Valley_Team_Non_Clinical_Member.role-meta.xml
  MAiD - Case Management App/force-app/main/default/roles/Cowichan_Valley_Team_Program_Leader.role-meta.xml
  MAiD - Case Management App/force-app/main/default/roles/Delta_Team_Admin.role-meta.xml
  MAiD - Case Management App/force-app/main/default/roles/Delta_Team_Clinical_Member.role-meta.xml
  MAiD - Case Management App/force-app/main/default/roles/Delta_Team_Non_Clinical_Member.role-meta.xml
  MAiD - Case Management App/force-app/main/default/roles/Delta_Team_Program_Leader.role-meta.xml
  MAiD - Case Management App/force-app/main/default/roles/Gold_Trail_Team_Admin.role-meta.xml
  MAiD - Case Management App/force-app/main/default/roles/Gold_Trail_Team_Clinical_Member.role-meta.xml
  MAiD - Case Management App/force-app/main/default/roles/Gold_Trail_Team_Non_Clinical_Member.role-meta.xml
  MAiD - Case Management App/force-app/main/default/roles/Gold_Trail_Team_Program_Leader.role-meta.xml
  MAiD - Case Management App/force-app/main/default/roles/Nicola_Similkameen_Team_Admin.role-meta.xml
  MAiD - Case Management App/force-app/main/default/roles/Nicola_Similkameen_Team_Clinical_Member.role-meta.xml
  MAiD - Case Management App/force-app/main/default/roles/Nicola_Similkameen_Team_Non_Clinical_Member.role-meta.xml
  MAiD - Case Management App/force-app/main/default/roles/Nicola_Similkameen_Team_Program_Leader.role-meta.xml
  MAiD - Case Management App/force-app/main/default/roles/Peace_River_South_Team_Admin.role-meta.xml
  MAiD - Case Management App/force-app/main/default/roles/Peace_River_South_Team_Clinical_Member.role-meta.xml
  MAiD - Case Management App/force-app/main/default/roles/Peace_River_South_Team_Non_Clinical_Member.role-meta.xml
  MAiD - Case Management App/force-app/main/default/roles/Peace_River_South_Team_Program_Leader.role-meta.xml
  MAiD - Case Management App/force-app/main/default/roles/Qualicum_Team_Admin.role-meta.xml
  MAiD - Case Management App/force-app/main/default/roles/Qualicum_Team_Clinical_Member.role-meta.xml
  MAiD - Case Management App/force-app/main/default/roles/Qualicum_Team_Non_Clinical_Member.role-meta.xml
  MAiD - Case Management App/force-app/main/default/roles/Qualicum_Team_Program_Leader.role-meta.xml
  MAiD - Case Management App/force-app/main/default/roles/Surrey_Team_Admin.role-meta.xml
  MAiD - Case Management App/force-app/main/default/roles/Surrey_Team_Clinical_Member.role-meta.xml
  MAiD - Case Management App/force-app/main/default/roles/Surrey_Team_Non_Clinical_Member.role-meta.xml
  MAiD - Case Management App/force-app/main/default/roles/Surrey_Team_Program_Leader.role-meta.xml
  MAiD - Case Management App/force-app/main/default/sharingRules/Case.sharingRules-meta.xml
  MAiD - Case Management App/force-app/main/default/sharingRules/Referral__c.sharingRules-meta.xml
Labels: no merge

#818 BCMOHAD-25020 || Update formula field DIS_Q15
  MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/DIS_Q15__c.field-meta.xml
Labels: enhancement

#837 BCMOHAD-24814 || Updated the formula
  MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/PROC_Q185C__c.field-meta.xml
Labels: enhancement

#835 BCMOHAD-24605 || updated the Assessment of eligibility
  MAiD - Case Management App/force-app/main/default/flows/Status_update_prevention.flow-meta.xml
Labels: enhancement

#822 BCMOHAD-24840 || update lookup filter on ReturningPrescriberName
  MAiD - Case Management App/force-app/main/default/objects/Form_1641__c/fields/Returning_Prescriber_Name__c.field-meta.xml
Labels: enhancement

#836 BCMOHAD-24619 || Updated the formula field type
  MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/RAC_Q05I__c.field-meta.xml
Labels: enhancement

#842 BCMOHAD-24617 || Updated the formula
  MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/IND_Q05F__c.field-meta.xml
Labels: enhancement

#843 BCMOHAD-24748 || Updated the formula field RES_Q05
  MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/RES_Q05__c.field-meta.xml
Labels: enhancement

#844 BCMOHAD-24581 || Updated the page layout
  MAiD - Case Management App/force-app/main/default/layouts/Form_1641__c-Form 1641 Layout.layout-meta.xml
Labels: enhancement

#815 BCMOHAD-24777 || Update formula field ELG_Q37__c
  MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/ELG_Q37__c.field-meta.xml
Labels: enhancement

#840 BCMOHAD-25154 ||Update label for field
  MAiD - Case Management App/force-app/main/default/objects/Case/fields/If_Other_Preferred_Gender_Specify__c.field-meta.xml
Labels: enhancement

#833 BCMOHAD-24537 || Update Apex Class getCasePHNandUpdate
  MAiD - Case Management App/force-app/main/default/classes/GetCasePHNandVerify.cls
Labels: enhancement

#831 BCMOHAD-24595-2 || Update flow mandatory data rule 42 and 46
  MAiD - Case Management App/force-app/main/default/flows/Mandatory_Data.flow-meta.xml
Labels: enhancement

#816 BCMOHAD-24778 || Update formula field ELG_Q74
  MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/ELG_Q74__c.field-meta.xml
Labels: enhancement

#848 BCMOHAD-24748-V1|| Updated the Picklist value
  MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/RES_Q05__c.field-meta.xml
Labels: bug, enhancement

#850 BCMOHAD-24581-V1 || Updated the 1641 Page layout
  MAiD - Case Management App/force-app/main/default/layouts/Form_1641__c-Form 1641 Layout.layout-meta.xml
Labels: bug, enhancement

#817 BCMOHAD-24940 || Update formula field DIS_Q20
  MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/DIS_Q20__c.field-meta.xml
Labels: enhancement
