Repository bcgov/MOH-MAiD, pull requests merged in 2025-03, with the labels that each got.

#918 Bcmohad 27969 ICY Enhancements - #6 Add more case note “Mode Location” drop-down options
  MAiD - Case Management App/force-app/main/default/classes/ICY_BatchToSendInactiveCaseNotesTest.cls
  MAiD - Case Management App/force-app/main/default/classes/ICY_Notes_Documents_Controller.cls
  MAiD - Case Management App/force-app/main/default/classes/ytsCaseTriggerHandlerTest.cls
  MAiD - Case Management App/force-app/main/default/lwc/icyCreateEditNotes/icyCreateEditNotes.html
  MAiD - Case Management App/force-app/main/default/lwc/icyCreateEditNotes/icyCreateEditNotes.js
  MAiD - Case Management App/force-app/main/default/objects/ICY_Notes__c/fields/Mode_Location__c.field-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/ICY_Notes__c/fields/Other_Mode_Location__c.field-meta.xml
  MAiD - Case Management App/force-app/main/default/permissionsets/ICY_Integrate_Permissions.permissionset-meta.xml
Labels: enhancement

#921 BCMOHAD-28013 || Created New Field "Flagged Case"
  MAiD - Case Management App/force-app/main/default/layouts/Case-MAiD Case Layout.layout-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/Case/fields/Flagged_Case__c.field-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/Case/validationRules/Flagged_Case_field_edit_access.validationRule-meta.xml
  MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Analyst.permissionset-meta.xml
  MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Manager.permissionset-meta.xml
Labels: enhancement

#919 BCMOHAD 28035
  MAiD - Case Management App/force-app/main/default/flows/Update_Related_Case_Record.flow-meta.xml
  MAiD - Case Management App/force-app/main/default/layouts/Case-MAiD Case Layout.layout-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/Case/fields/Education_History__c.field-meta.xml
  MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Analyst.permissionset-meta.xml
  MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Manager.permissionset-meta.xml
  MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_System_Administrator.permissionset-meta.xml
Labels: enhancement

#922 BCMOHAD 28017
  MAiD - Case Management App/force-app/main/default/sharingRules/Case.sharingRules-meta.xml
Labels: enhancement

#924 BCMOHAD-28042_v1 || 1633 Assessment Date Validation Rule
  MAiD - Case Management App/force-app/main/default/objects/Form_1633__c/validationRules/Assessment_date_check.validationRule-meta.xml
Labels: enhancement

#920 BCMOHAD-27970-Update Person Birthdate
  MAiD - Case Management App/force-app/main/default/classes/ICY_CompleteIntakeCtrl.cls
  MAiD - Case Management App/force-app/main/default/flows/ICY_Referral_Update_PersonBirthdate.flow-meta.xml
Labels: enhancement

#926 BCMOHAD 28039
  MAiD - Case Management App/force-app/main/default/layouts/Form_1633__c-Form 1633 Layout.layout-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/Form_1633__c/fields/Case_Owner__c.field-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/Form_1633__c/fields/Case_Type_Reported_Date__c.field-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/Form_1633__c/fields/Case_Type__c.field-meta.xml
  MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Analyst.permissionset-meta.xml
  MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Manager.permissionset-meta.xml
Labels: enhancement

#927 BCMOHAD 28039 v1
  MAiD - Case Management App/force-app/main/default/flexipages/Practitioner_Page.flexipage-meta.xml
  MAiD - Case Management App/force-app/main/default/groups/All_MAiD_Analyst.group-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/Account/listViews/AllAccounts.listView-meta.xml
Labels: enhancement

#928 BCMOHAD-28043 || Validation rule 1634
  MAiD - Case Management App/force-app/main/default/objects/Form_1634__c/validationRules/Assessment_date_check.validationRule-meta.xml
Labels: enhancement

#929 BCMOHAD-28018-28020-28031 || Formula update
  MAiD - Case Management App/.sf/config.json
  MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/DIS_Q05__c.field-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/DIS_Q20__c.field-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/RES_Q10__c.field-meta.xml
Labels: enhancement

#930 BCMOHAD-28013-V1 || Updated the formula, Description and error message
  MAiD - Case Management App/force-app/main/default/objects/Case/validationRules/Flagged_Case_field_edit_access.validationRule-meta.xml
Labels: bug

#932 BCMOHAD-28035 v1 || Flow fix
  MAiD - Case Management App/force-app/main/default/flows/Update_Related_Case_Record.flow-meta.xml
Labels: enhancement

#933 BCMOHAD-28015 && BCMOHAD-28016 || Created New fields and Validation Rules
  MAiD - Case Management App/force-app/main/default/layouts/Case-MAiD Case Layout.layout-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/Case/fields/Reason_for_Flagging__c.field-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/Case/validationRules/Reason_for_Flagging_cannot_be_null.validationRule-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/Case/validationRules/Reason_for_Flagging_case_Edit.validationRule-meta.xml
  MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Analyst.permissionset-meta.xml
  MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Manager.permissionset-meta.xml
Labels: enhancement

#931 BCMAHAD-28038 || Formula fix and flexipage fix.
  MAiD - Case Management App/force-app/main/default/flexipages/Practitioner_Page.flexipage-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/Form_1633__c/fields/Case_Owner__c.field-meta.xml
Labels: enhancement

#925 BCMOHAD-28099-NewFieldsFlowReportFolderReport
  MAiD - Case Management App/force-app/main/default/flows/ICY_Update_ICY_Last_Case_Note_Date.flow-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/Case/fields/ICY_Last_Case_Note_Date__c.field-meta.xml
  MAiD - Case Management App/force-app/main/default/objects/Case/fields/ICY_Last_Reported_Date__c.field-meta.xml
  MAiD - Case Management App/force-app/main/default/permissionsets/ICY_Integrate_Permissions.permissionset-meta.xml
  MAiD - Case Management App/force-app/main/default/reports/ICYReportsPL.reportFolder-meta.xml
  MAiD - Case Management App/force-app/main/default/reports/ICYReportsPL/Cases_with_no_case_notes_in_last_30_days_t9c.report-meta.xml
Labels: enhancement

#935 BCMOHAD-28015-V1 || Updated the error message
  MAiD - Case Management App/force-app/main/default/objects/Case/validationRules/Reason_for_Flagging_case_Edit.validationRule-meta.xml
Labels: bug, enhancement

#937 BCMOHAD-28099-1 updating Report
  MAiD - Case Management App/force-app/main/default/reports/ICYReportsPL/Cases_with_no_case_notes_in_last_30_days_t9c.report-meta.xml
Labels: enhancement

#938 Bcmohad 27969 1
  MAiD - Case Management App/force-app/main/default/classes/ICY_Notes_Documents_Controller.cls
  MAiD - Case Management App/force-app/main/default/lwc/iCY_NotesComponent/iCY_NotesComponent.html
  MAiD - Case Management App/force-app/main/default/lwc/icyCreateEditNotes/icyCreateEditNotes.js
Labels: enhancement

#939 BCMOHAD-28034 || Updated the formula
  MAiD - Case Management App/force-app/main/default/objects/S1_HC_2023__c/fields/ADM_Q25__c.field-meta.xml
Labels: enhancement

#940 BCMOHAD 28036 v1 || MAiD Analyst Permission set update
  MAiD - Case Management App/force-app/main/default/permissionsets/MAiD_Analyst.permissionset-meta.xml
Labels: enhancement
